package com.mzs.costom.model;

import java.io.Serializable;

public class Sysmenu implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmenu.menuid
     *
     * @mbg.generated Tue Sep 05 14:46:47 CST 2017
     */
    private Long menuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmenu.menuname
     *
     * @mbg.generated Tue Sep 05 14:46:47 CST 2017
     */
    private String menuname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysmenu.parentid
     *
     * @mbg.generated Tue Sep 05 14:46:47 CST 2017
     */
    private Long parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sysmenu
     *
     * @mbg.generated Tue Sep 05 14:46:47 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmenu.menuid
     *
     * @return the value of sysmenu.menuid
     *
     * @mbg.generated Tue Sep 05 14:46:47 CST 2017
     */
    public Long getMenuid() {
        return menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmenu.menuid
     *
     * @param menuid the value for sysmenu.menuid
     *
     * @mbg.generated Tue Sep 05 14:46:47 CST 2017
     */
    public void setMenuid(Long menuid) {
        this.menuid = menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmenu.menuname
     *
     * @return the value of sysmenu.menuname
     *
     * @mbg.generated Tue Sep 05 14:46:47 CST 2017
     */
    public String getMenuname() {
        return menuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmenu.menuname
     *
     * @param menuname the value for sysmenu.menuname
     *
     * @mbg.generated Tue Sep 05 14:46:47 CST 2017
     */
    public void setMenuname(String menuname) {
        this.menuname = menuname == null ? null : menuname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysmenu.parentid
     *
     * @return the value of sysmenu.parentid
     *
     * @mbg.generated Tue Sep 05 14:46:47 CST 2017
     */
    public Long getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysmenu.parentid
     *
     * @param parentid the value for sysmenu.parentid
     *
     * @mbg.generated Tue Sep 05 14:46:47 CST 2017
     */
    public void setParentid(Long parentid) {
        this.parentid = parentid;
    }
}