package com.mzs.costom.model;

import java.io.Serializable;

public class Sysrole implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysrole.roleid
     *
     * @mbg.generated Tue Sep 05 14:46:47 CST 2017
     */
    private Long roleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysrole.rolename
     *
     * @mbg.generated Tue Sep 05 14:46:47 CST 2017
     */
    private String rolename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sysrole
     *
     * @mbg.generated Tue Sep 05 14:46:47 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysrole.roleid
     *
     * @return the value of sysrole.roleid
     *
     * @mbg.generated Tue Sep 05 14:46:47 CST 2017
     */
    public Long getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysrole.roleid
     *
     * @param roleid the value for sysrole.roleid
     *
     * @mbg.generated Tue Sep 05 14:46:47 CST 2017
     */
    public void setRoleid(Long roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysrole.rolename
     *
     * @return the value of sysrole.rolename
     *
     * @mbg.generated Tue Sep 05 14:46:47 CST 2017
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysrole.rolename
     *
     * @param rolename the value for sysrole.rolename
     *
     * @mbg.generated Tue Sep 05 14:46:47 CST 2017
     */
    public void setRolename(String rolename) {
        this.rolename = rolename == null ? null : rolename.trim();
    }
}