package com.mzs.costom.model;

import java.io.Serializable;
import java.util.Date;

public class Sysuser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.userid
     *
     * @mbg.generated Tue Sep 05 14:46:47 CST 2017
     */
    private Long userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.username
     *
     * @mbg.generated Tue Sep 05 14:46:47 CST 2017
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.password
     *
     * @mbg.generated Tue Sep 05 14:46:47 CST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.status
     *
     * @mbg.generated Tue Sep 05 14:46:47 CST 2017
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.createtime
     *
     * @mbg.generated Tue Sep 05 14:46:47 CST 2017
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.updatetime
     *
     * @mbg.generated Tue Sep 05 14:46:47 CST 2017
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.createid
     *
     * @mbg.generated Tue Sep 05 14:46:47 CST 2017
     */
    private Long createid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.updateid
     *
     * @mbg.generated Tue Sep 05 14:46:47 CST 2017
     */
    private Long updateid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.roleid
     *
     * @mbg.generated Tue Sep 05 14:46:47 CST 2017
     */
    private Long roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sysuser
     *
     * @mbg.generated Tue Sep 05 14:46:47 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuser.userid
     *
     * @return the value of sysuser.userid
     *
     * @mbg.generated Tue Sep 05 14:46:47 CST 2017
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuser.userid
     *
     * @param userid the value for sysuser.userid
     *
     * @mbg.generated Tue Sep 05 14:46:47 CST 2017
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuser.username
     *
     * @return the value of sysuser.username
     *
     * @mbg.generated Tue Sep 05 14:46:47 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuser.username
     *
     * @param username the value for sysuser.username
     *
     * @mbg.generated Tue Sep 05 14:46:47 CST 2017
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuser.password
     *
     * @return the value of sysuser.password
     *
     * @mbg.generated Tue Sep 05 14:46:47 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuser.password
     *
     * @param password the value for sysuser.password
     *
     * @mbg.generated Tue Sep 05 14:46:47 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuser.status
     *
     * @return the value of sysuser.status
     *
     * @mbg.generated Tue Sep 05 14:46:47 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuser.status
     *
     * @param status the value for sysuser.status
     *
     * @mbg.generated Tue Sep 05 14:46:47 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuser.createtime
     *
     * @return the value of sysuser.createtime
     *
     * @mbg.generated Tue Sep 05 14:46:47 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuser.createtime
     *
     * @param createtime the value for sysuser.createtime
     *
     * @mbg.generated Tue Sep 05 14:46:47 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuser.updatetime
     *
     * @return the value of sysuser.updatetime
     *
     * @mbg.generated Tue Sep 05 14:46:47 CST 2017
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuser.updatetime
     *
     * @param updatetime the value for sysuser.updatetime
     *
     * @mbg.generated Tue Sep 05 14:46:47 CST 2017
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuser.createid
     *
     * @return the value of sysuser.createid
     *
     * @mbg.generated Tue Sep 05 14:46:47 CST 2017
     */
    public Long getCreateid() {
        return createid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuser.createid
     *
     * @param createid the value for sysuser.createid
     *
     * @mbg.generated Tue Sep 05 14:46:47 CST 2017
     */
    public void setCreateid(Long createid) {
        this.createid = createid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuser.updateid
     *
     * @return the value of sysuser.updateid
     *
     * @mbg.generated Tue Sep 05 14:46:47 CST 2017
     */
    public Long getUpdateid() {
        return updateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuser.updateid
     *
     * @param updateid the value for sysuser.updateid
     *
     * @mbg.generated Tue Sep 05 14:46:47 CST 2017
     */
    public void setUpdateid(Long updateid) {
        this.updateid = updateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuser.roleid
     *
     * @return the value of sysuser.roleid
     *
     * @mbg.generated Tue Sep 05 14:46:47 CST 2017
     */
    public Long getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuser.roleid
     *
     * @param roleid the value for sysuser.roleid
     *
     * @mbg.generated Tue Sep 05 14:46:47 CST 2017
     */
    public void setRoleid(Long roleid) {
        this.roleid = roleid;
    }
}